info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

spring:
  application:
    name: profile
  profiles:
    active: @spring.profiles.active@


management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8083
