spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/c-api/v1/**
        - id: producer
          uri: lb://producer
          predicates:
            - Path=/p-api/v1/**

server:
  port: 8070




feign:
  hystrix:
    enabled: true

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 15
    serviceUrl:
      defaultZone: http://localhost:8761/eureka




management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"