spring:
  application:
    name: consumer
server:
  port: 8060

feign:
  hystrix:
    enabled: true

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 15
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    registry-fetch-interval-seconds: 30
#  instance:
#    lease-renewal-interval-in-seconds: 30
#    health-check-url-path: /actuator/health
##health endpoint是否必须显示全部细节。默认情况下, /actuator/health 是公开的，并且不显示细节。
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        #选择暴露的端点
#        include: "info,health,env,beans"
#        #不暴露的端点
#        exclude: "env"
