server:
  port: 8810

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth2_db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password:
  redis:
    host: 127.0.0.1
    database: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging.level.org.springframework.security: DEBUG